flowchart TB
    FIL["FILIAL"]
    FUN["FUNCIONARIO"]
    CLI["CLIENTE"]
    CAT["CATEGORIA"]
    VEI["VEICULO"]
    LOC["LOCACAO"]
    PAG["PAGAMENTO"]

    FIL ---|"(1,1)"| rlota{"lota"}
    rlota ---|"(1,N)"| FUN
    FUN ---|"(1,1)"| rger{"gerencia"}
    rger ---|"(0,1)"| FIL
    FIL ---|"(1,1)"| rman{"mantém"}
    rman ---|"(1,N)"| VEI
    CAT ---|"(1,1)"| rcla{"classifica"}
    rcla ---|"(1,N)"| VEI
    CLI ---|"(1,1)"| rrea{"realiza"}
    rrea ---|"(0,N)"| LOC
    FUN ---|"(1,1)"| rreg{"registra"}
    rreg ---|"(0,N)"| LOC
    subgraph AEINC["ITEM_LOCACAO (valor_diária)"]
      rinc{"inclui"}
    end
    LOC ---|"(0,N)"| rinc
    rinc ---|"(1,N)"| VEI
    LOC ---|"(1,1)"| rgera{"gera"}
    rgera ---|"(1,N)"| PAG

    classDef ent fill:#dfe8f3,stroke:#12437f,stroke-width:2px,color:#0d2b57;
    classDef rel fill:#eef4fb,stroke:#4f6d94,color:#0d2b57;
    class FIL,FUN,CLI,CAT,VEI,LOC,PAG ent;
    class rlota,rger,rman,rcla,rrea,rreg,rinc,rgera rel;
