erDiagram
  MATERIAIS ||--o{ MATERIAIS : "COMPOEM (auto-rel.)"
  MATERIAIS }o--o{ PROJETOS : CONSOMEM
  MATERIAIS ||--|| FABRICACAO_INTERNA : "é um (generalização)"
  MATERIAIS ||--|| COMPRADOS : "é um (generalização)"
  FABRICACAO_INTERNA }o--o{ COMPRADOS : UTILIZAM
  COMPRADOS }o--|| EMPREGADOS : COMPRAM
  PROJETOS }o--o{ EMPREGADOS : "ATUAM · ALOCAÇÃO (início/fim)"
  EMPREGADOS }o--|| CARGOS : POSSUEM
  REPRESENTANTES }o--o{ CLIENTES : COMPRAM
  REPRESENTANTES }o--o{ ARMAZENS : ALUGAM
  REPRESENTANTES }o--o{ ARMAZENS : AVALIAM
  ARMAZENS |o--|| LOCAIS : "SITUAM-SE"