erDiagram
  materiais ||--o{ composicao : "auto-rel M:N"
  materiais ||--o{ consumo : ""
  projetos ||--o{ consumo : "M:N"
  materiais ||--|| fabricacaointerna : "generalização"
  materiais ||--|| comprados : "generalização"
  fabricacaointerna ||--o{ uso : ""
  comprados ||--o{ uso : ""
  projetos ||--o{ alocacao : ""
  empregados ||--o{ alocacao : "agregação"
  CARGOS ||--o{ empregados : "1:N"
  representantes ||--o{ compras : ""
  clientes ||--o{ compras : "M:N"
  representantes ||--o{ alugueis : ""
  armazens ||--o{ alugueis : "M:N"
  representantes ||--o{ avalistas : ""
  armazens ||--o{ avalistas : "M:N"
  locais ||--o{ armazens : "1:N"
  clientes ||--o{ telefones : "multivalorado"