erDiagram
    NOTAS_FISCAIS ||--o{ ITENS_NF : discriminam
    NOTAS_FISCAIS {
        int numero PK
        date data
        numeric valor
    }
    ITENS_NF {
        int numero PK "FK"
        int item PK
        int quantidade
        numeric valor
    }
