erDiagram
    FORNECEDORES ||--o{ FORNECIMENTOS : tem
    PRODUTOS ||--o{ FORNECIMENTOS : em
    FORNECEDORES {
        int codigo PK "not null"
        varchar nome "not null"
    }
    PRODUTOS {
        int codigo PK "not null"
        varchar nome "not null"
    }
    FORNECIMENTOS {
        int cod_fornecedor PK,FK "not null"
        int cod_produto PK,FK "not null"
        numeric preco "not null"
    }
