--A
SELECT * 
  FROM ALUNOS;

--B
SELECT MATRICULA_ALUNO
     , INITCAP(NOME_ALUNO) AS NOME_ALUNO
     , TO_DATE(DATA_NASCIMENTO, 'DD/MM/YYYY') AS DATA_NASCIMENTO
  FROM ALUNOS 
 WHERE DATA_NASCIMENTO <= TO_DATE('01/01/2000', 'DD/MM/YYYY');

--C
SELECT COUNT(1) 
   FROM ALUNOS 
  WHERE DATA_NASCIMENTO >= TO_DATE('01/01/2000', 'DD/MM/YYYY');

--D
SELECT A.NOME_ALUNO
     , '(' || SUBSTR(T.TELEFONE, 1, 2) || ') ' || SUBSTR(T.TELEFONE, 3, 1) || SUBSTR(T.TELEFONE, 4, 4) || '-' || SUBSTR(T.TELEFONE, 8, 4) AS TELEFONE
  FROM ALUNOS A
  INNER JOIN TELEFONES_ALUNOS T
  ON A.MATRICULA_ALUNO = T.MATRICULA_ALUNO
 ORDER BY A.NOME_ALUNO;
 
--E
SELECT * 
  FROM ALUNOS 
 WHERE NOME_ALUNO LIKE '%ANTONIO%';

--F
SELECT * 
  FROM PROFESSORES P 
 WHERE NOT EXISTS (SELECT 1 
                     FROM OFERTAS O 
                    WHERE O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR);
                    
--G
SELECT * 
  FROM DISCIPLINAS 
 WHERE CODIGO_DISCIPLINA IN (85853, 75189);
 
--H
SELECT *
  FROM DISCIPLINAS
 WHERE CODIGO_DISCIPLINA_DEPENDENCIA IS NULL;
 
--I
SELECT TO_CHAR(O.HORARIO_INICIAL, 'HH24:MI') AS HORARIO_INICIAL
     , TO_CHAR(O.HORARIO_FINAL, 'HH24:MI') AS HORARIO_FINAL
     , P.NOME_PROFESSOR
  FROM OFERTAS O
  INNER JOIN PROFESSORES P
  ON O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR
 WHERE P.MATRICULA_PROFESSOR = 55125;
 
--J
SELECT A.NOME_ALUNO
     , AO.SEMESTRE
     , TO_CHAR(O.HORARIO_INICIAL, 'HH24:MI') AS HORARIO_INICIAL
     , TO_CHAR(O.HORARIO_FINAL, 'HH24:MI') AS HORARIO_FINAL
     , LOWER(O.DIA_SEMANA) AS DIA_SEMANA
     , D.NOME_DISCIPLINA
     , P.NOME_PROFESSOR
     , D.CARGA_HORARIA
  FROM ALUNOS_OFERTAS AO
  INNER JOIN OFERTAS O
  ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
  INNER JOIN ALUNOS A
  ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
  INNER JOIN PROFESSORES P
  ON O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR
  INNER JOIN DISCIPLINAS D
  ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA
 WHERE D.CODIGO_DISCIPLINA_DEPENDENCIA IS NOT NULL
 ORDER BY A.NOME_ALUNO;
 
--K
SELECT D.NOME_DISCIPLINA AS PRE_REQUISITO
     , DD.NOME_DISCIPLINA AS DISCIPLINA
  FROM DISCIPLINAS D
  INNER JOIN DISCIPLINAS DD
  ON D.CODIGO_DISCIPLINA = DD.CODIGO_DISCIPLINA_DEPENDENCIA
ORDER BY 1, 2;

--L
SELECT COUNT(1) AS TOTAL_DISCIPLINAS
     , P.NOME_PROFESSOR
  FROM OFERTAS O
  INNER JOIN DISCIPLINAS D
  ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA
  INNER JOIN PROFESSORES P
  ON O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR
 GROUP BY P.NOME_PROFESSOR
 ORDER BY P.NOME_PROFESSOR;