--A
DELETE FROM DISCIPLINAS WHERE CODIGO_DISCIPLINA IN (85853, 75189);
--B
DELETE FROM OFERTAS WHERE CODIGO_OFERTA = 1742;
--C
DELETE FROM PROFESSORES P WHERE NOT EXISTS (SELECT 1 FROM OFERTAS O WHERE O.MATRICULA_PROFESSOR = P.MATRICULA_PROFESSOR);
--D
DELETE FROM TELEFONES_ALUNOS WHERE TELEFONE LIKE '27%';
--E
ROLLBACK;