/*FASE 1*/
--a
SELECT CLI.*
  FROM CLIENTES CLI;

--b
SELECT PRO.NOME_PRODUTO
  FROM PRODUTOS PRO;

--c
SELECT DISTINCT CLI.CIDADE
      , CLI.UF
      , CLI.CEP
  FROM CLIENTES CLI
 ORDER BY CLI.UF;

SELECT CLI.CIDADE
     , CLI.UF
     , CLI.CEP
  FROM CLIENTES CLI
 ORDER BY CLI.UF;

--d
SELECT PED.*
  FROM PEDIDOS PED
 WHERE PED.CODIGO_CLIENTE = 4
   AND PED.VALOR_LIQUIDO > 10000;

--e
SELECT PED.*
  FROM PEDIDOS PED
 WHERE PED.VALOR_TOTAL NOT BETWEEN 100 AND 5000
   AND PED.DATA_PEDIDO BETWEEN TO_DATE('13/01/2007', 'DD/MM/YYYY') AND TO_DATE('14/01/2007', 'DD/MM/YYYY');

--f
SELECT CLI.*
  FROM CLIENTES CLI
 WHERE CLI.CODIGO_CLIENTE < 5
    OR CLI.CODIGO_CLIENTE > 25;

--g
SELECT PRO.*
  FROM PRODUTOS PRO
 WHERE UPPER(PRO.NOME_PRODUTO) LIKE 'M%AN%A';

--h
SELECT PRO.*
  FROM PRODUTOS PRO
 WHERE UPPER(PRO.NOME_PRODUTO) LIKE 'MA______';

--i
SELECT PRO.*
  FROM PRODUTOS PRO
 WHERE UPPER(PRO.NOME_PRODUTO) LIKE '__ACA%';

--j
SELECT PRO.*
  FROM PRODUTOS PRO
 WHERE UPPER(PRO.NOME_PRODUTO) LIKE '%A\_P%' ESCAPE '\';

--k
SELECT CLI.*
  FROM CLIENTES CLI
 WHERE CLI.UF IN ('ES', 'MG');

--l
SELECT CLI.*
  FROM CLIENTES CLI
 WHERE CLI.UF NOT IN ('RJ', 'SP');

/*FASE 2*/
--m
SELECT PRO.NOME_PRODUTO AS "NOME DO PRODUTO"
     , PRO.PRECO_PRODUTO AS "PREÇO DO PRODUTO"
     , UE.DESCRICAO_UNIDADE_MEDIDA AS "DESCRIÇÃO DA UNIDADE DE ESTOQUE"
  FROM PRODUTOS PRO
  INNER JOIN UNIDADE_MEDIDA UE
  ON PRO.CODIGO_UNIDADE_MEDIDA = UE.CODIGO_UNIDADE_MEDIDA
 WHERE (PRO.PRECO_PRODUTO < 20 OR PRO.PRECO_PRODUTO IS NULL)
   AND UE.DESCRICAO_UNIDADE_MEDIDA IN ('KILOGRAMA', 'LITRO');

--n
SELECT PED.CODIGO_PEDIDO
     , CLI.CODIGO_CLIENTE
     , CLI.NOME_CLIENTE
     , PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , UE.DESCRICAO_UNIDADE_MEDIDA
  FROM PEDIDOS PED
  INNER JOIN CLIENTES CLI
  ON PED.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE
  INNER JOIN ITENS_PEDIDOS ITE
  ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
  INNER JOIN PRODUTOS PRO
  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
  INNER JOIN UNIDADE_MEDIDA UE
  ON PRO.CODIGO_UNIDADE_MEDIDA = UE.CODIGO_UNIDADE_MEDIDA;

--o
SELECT PRO.CODIGO_PRODUTO AS CODIGO
     , PRO.NOME_PRODUTO AS NOME
     , PRO.PRECO_PRODUTO AS "PREÇO ATUAL"
     , (PRO.PRECO_PRODUTO * 1.3) AS "PREÇO PROJETADO"
  FROM PRODUTOS PRO
 WHERE PRO.CODIGO_PRODUTO IN (SELECT ITE.CODIGO_PRODUTO
                                FROM ITENS_PEDIDOS ITE);

/*FASE 3*/
--p
SELECT CLI.CODIGO_CLIENTE
     , CLI.NOME_CLIENTE
     , SUM(PED.VALOR_TOTAL) AS TOTAL_CLIENTE
  FROM CLIENTES CLI
  INNER JOIN PEDIDOS PED
  ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
 GROUP BY CLI.CODIGO_CLIENTE, CLI.NOME_CLIENTE
 ORDER BY TOTAL_CLIENTE DESC;

--q
SELECT COUNT(1)
  FROM PEDIDOS PED
 WHERE PED.CODIGO_CLIENTE = 5;

--r
SELECT MIN(PED.VALOR_TOTAL) AS MINIMO
     , MAX(PED.VALOR_TOTAL) AS MAXIMO
     , SUM(PED.VALOR_TOTAL) AS TOTAL
     , ROUND(AVG(PED.VALOR_TOTAL),2) AS MEDIA_1
     , TRUNC(AVG(PED.VALOR_TOTAL),2) AS MEDIA_2
  FROM PEDIDOS PED;

--s
SELECT ITE.CODIGO_PRODUTO
     , TRUNC(AVG(ITE.QUANTIDADE),2) AS MEDIA
  FROM ITENS_PEDIDOS ITE
 GROUP BY ITE.CODIGO_PRODUTO
 ORDER BY ITE.CODIGO_PRODUTO;

--t
SELECT CLI.UF
     , COUNT(CLI.CODIGO_CLIENTE) AS QUANTIDADE_CLIENTES
  FROM CLIENTES CLI
 WHERE CLI.CODIGO_CLIENTE IN (SELECT PED.CODIGO_CLIENTE FROM PEDIDOS PED)
 GROUP BY CLI.UF
 ORDER BY QUANTIDADE_CLIENTES DESC;

--u
SELECT CLI.CODIGO_CLIENTE
     , ROUND(AVG(PED.VALOR_TOTAL),2) AS MEDIA_POR_CLIENTE
  FROM CLIENTES CLI
  INNER JOIN PEDIDOS PED
  ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
 GROUP BY CLI.CODIGO_CLIENTE
 HAVING ROUND(AVG(PED.VALOR_TOTAL),2) > 8000
 ORDER BY MEDIA_POR_CLIENTE;

--v
SELECT PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , SUM(ITE.VALOR_TOTAL_ITEM) TOTAL_POR_PRODUTO
  FROM PRODUTOS PRO
  INNER JOIN ITENS_PEDIDOS ITE
  ON PRO.CODIGO_PRODUTO = ITE.CODIGO_PRODUTO
 GROUP BY PRO.CODIGO_PRODUTO
        , PRO.NOME_PRODUTO
 HAVING SUM(ITE.VALOR_TOTAL_ITEM) > 800
 ORDER BY TOTAL_POR_PRODUTO DESC;

--w
SELECT PRO.*
  FROM PRODUTOS PRO
  LEFT OUTER JOIN ITENS_PEDIDOS ITE
  ON PRO.CODIGO_PRODUTO = ITE.CODIGO_PRODUTO
 WHERE ITE.CODIGO_PRODUTO IS NULL;

--x
SELECT PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , PRO.PRECO_PRODUTO
  FROM PRODUTOS PRO
 WHERE PRO.PRECO_PRODUTO > (SELECT AVG(PRO.PRECO_PRODUTO) FROM PRODUTOS PRO);

--y
SELECT PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , PRO.PRECO_PRODUTO
  FROM PRODUTOS PRO  
 WHERE PRO.PRECO_PRODUTO > (SELECT AVG(PRO.PRECO_PRODUTO) FROM PRODUTOS PRO)
   AND UPPER(PRO.CODIGO_UNIDADE_MEDIDA) IN ('KG', 'UM', 'L')
   AND UPPER(PRO.NOME_PRODUTO) LIKE '%H%';


/*FASE 4*/
--z
SELECT CLI.*
  FROM CLIENTES CLI
 WHERE CLI.CODIGO_CLIENTE IN (SELECT PED.CODIGO_CLIENTE
                                FROM PEDIDOS PED
                               WHERE PED.DATA_PEDIDO = TO_DATE('13/01/2007', 'DD/MM/YYYY'))
   AND CLI.CODIGO_CLIENTE NOT IN (SELECT PED.CODIGO_CLIENTE
                                    FROM PEDIDOS PED
                                   WHERE PED.DATA_PEDIDO = TO_DATE('02/01/2007', 'DD/MM/YYYY'));
--aa
SELECT PRO.*
  FROM PRODUTOS PRO
 WHERE PRO.CODIGO_PRODUTO NOT IN (SELECT ITE.CODIGO_PRODUTO
                                    FROM ITENS_PEDIDOS ITE
                                    INNER JOIN PEDIDOS PED
                                    ON ITE.CODIGO_PEDIDO = PED.CODIGO_PEDIDO
                                    INNER JOIN CLIENTES CLI
                                    ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
                                   WHERE CLI.UF = 'RJ');

--bb
SELECT CLI.NOME_CLIENTE
     , CLI.TELEFONE, CLI.CODIGO_CLIENTE
  FROM CLIENTES CLI
 WHERE CLI.CODIGO_CLIENTE IN (SELECT PED.CODIGO_CLIENTE
                                FROM PEDIDOS PED
                               INNER JOIN ITENS_PEDIDOS ITE
                                  ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
                               INNER JOIN PRODUTOS PRO
                                  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
                               WHERE UPPER(PRO.NOME_PRODUTO) = 'ARROZ')
  AND CLI.CODIGO_CLIENTE NOT IN (SELECT PED.CODIGO_CLIENTE
                                   FROM PEDIDOS PED
                                  INNER JOIN ITENS_PEDIDOS ITE
                                     ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
                                  INNER JOIN PRODUTOS PRO
                                     ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
                                  WHERE UPPER(PRO.NOME_PRODUTO) = 'FEIJAO');

--cc
SELECT CLI.NOME_CLIENTE
     , CLI.TELEFONE
     , UF.DESCRICAO_UF
  FROM CLIENTES CLI
 INNER JOIN UF
    ON CLI.UF = UF.UF
 WHERE CLI.CODIGO_CLIENTE NOT IN (SELECT PED.CODIGO_CLIENTE
                                    FROM PEDIDOS PED)
    OR CLI.CODIGO_CLIENTE IN (SELECT PED.CODIGO_CLIENTE
                                FROM PEDIDOS PED
                               WHERE PED.VALOR_TOTAL > (SELECT SUM(PED.VALOR_TOTAL) 
                                                          FROM PEDIDOS PED 
                                                         WHERE PED.DATA_PEDIDO = TO_DATE('01/01/2007', 'DD/MM/YYYY')));

/*FASE 5*/
--dd
SELECT PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , PRO.PRECO_PRODUTO
     , SUM(PED.VALOR_TOTAL) TOTAL_POR_PRODUTO
  FROM PRODUTOS PRO
  LEFT JOIN ITENS_PEDIDOS ITE
  ON PRO.CODIGO_PRODUTO = ITE.CODIGO_PRODUTO
  LEFT JOIN PEDIDOS PED
  ON ITE.CODIGO_PEDIDO = PED.CODIGO_PEDIDO
  GROUP BY PRO.CODIGO_PRODUTO
         , PRO.NOME_PRODUTO
         , PRO.PRECO_PRODUTO
  ORDER BY TOTAL_POR_PRODUTO NULLS FIRST;

--ee
SELECT CLI.NOME_CLIENTE
     , PRO.NOME_PRODUTO
  FROM CLIENTES CLI
  LEFT JOIN PEDIDOS PED
  ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
  LEFT JOIN ITENS_PEDIDOS ITE
  ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
  LEFT JOIN PRODUTOS PRO
  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
 ORDER BY CLI.NOME_CLIENTE;

/*FASE 6*/
--ff
SELECT PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , UE.DESCRICAO_UNIDADE_MEDIDA
     , PRO.PRECO_PRODUTO
     , PRO.QUANTIDADE_ESTOQUE
     , SUM(PED.VALOR_TOTAL) TOTAL_VENDIDO
     , ( SELECT SUM(PED.VALOR_TOTAL) AS TOTAL_VENDIDO
                                   FROM PEDIDOS PED
                                  INNER JOIN ITENS_PEDIDOS ITE
                                  ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
                                  INNER JOIN PRODUTOS PRO
                                  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
                                  WHERE UPPER(PRO.NOME_PRODUTO) = 'SAL') AS TOTAL_VENDIDO_SAL
  FROM PRODUTOS PRO
  INNER JOIN UNIDADE_MEDIDA UE
  ON PRO.CODIGO_UNIDADE_MEDIDA = UE.CODIGO_UNIDADE_MEDIDA
  INNER JOIN ITENS_PEDIDOS ITE
  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
  INNER JOIN PEDIDOS PED
  ON ITE.CODIGO_PEDIDO = PED.CODIGO_PEDIDO
 GROUP BY PRO.CODIGO_PRODUTO
        , PRO.NOME_PRODUTO
        , UE.DESCRICAO_UNIDADE_MEDIDA
        , PRO.PRECO_PRODUTO
        , PRO.QUANTIDADE_ESTOQUE
 HAVING SUM(PED.VALOR_TOTAL) > ( SELECT SUM(PED.VALOR_TOTAL) AS TOTAL_VENDIDO
                                   FROM PEDIDOS PED
                                  INNER JOIN ITENS_PEDIDOS ITE
                                  ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
                                  INNER JOIN PRODUTOS PRO
                                  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
                                  WHERE UPPER(PRO.NOME_PRODUTO) = 'SAL')
ORDER BY TOTAL_VENDIDO DESC;

--gg
SELECT PRO.CODIGO_PRODUTO
     , PRO.NOME_PRODUTO
     , SUM(PED.VALOR_TOTAL) TOTAL_VENDIDO
     , (SELECT SUM(PED.VALOR_TOTAL)
          FROM PRODUTOS PRO
          INNER JOIN ITENS_PEDIDOS ITE
          ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
          INNER JOIN PEDIDOS PED
          ON ITE.CODIGO_PEDIDO = PED.CODIGO_PEDIDO
          INNER JOIN CLIENTES CLI
          ON PED.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE
          WHERE UPPER(CLI.CIDADE) = 'VILA VELHA') AS TOTAL_VITORIA
  FROM PRODUTOS PRO
  INNER JOIN ITENS_PEDIDOS ITE
  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
  INNER JOIN PEDIDOS PED
  ON ITE.CODIGO_PEDIDO = PED.CODIGO_PEDIDO
  INNER JOIN CLIENTES CLI
  ON PED.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE
  WHERE UPPER(CLI.CIDADE) = 'VITORIA'
 GROUP BY PRO.CODIGO_PRODUTO
        , PRO.NOME_PRODUTO
 HAVING SUM(PED.VALOR_TOTAL) > (SELECT SUM(PED.VALOR_TOTAL)
                                  FROM PRODUTOS PRO
                                  INNER JOIN ITENS_PEDIDOS ITE
                                  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
                                  INNER JOIN PEDIDOS PED
                                  ON ITE.CODIGO_PEDIDO = PED.CODIGO_PEDIDO
                                  INNER JOIN CLIENTES CLI
                                  ON PED.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE
                                  WHERE UPPER(CLI.CIDADE) = 'VILA VELHA');
                                  
--hh
SELECT CLI.CODIGO_CLIENTE
     , CLI.NOME_CLIENTE
     , MAX(ITE.QUANTIDADE) MAIOR_QUANTIDADE
     , PRO.NOME_PRODUTO     
     , (SELECT MAX(ITE3.QUANTIDADE) MAIOR_QUANTIDADE
              FROM CLIENTES CLI3
              INNER JOIN PEDIDOS PED3
              ON CLI3.CODIGO_CLIENTE = PED3.CODIGO_CLIENTE
              INNER JOIN ITENS_PEDIDOS ITE3
              ON PED3.CODIGO_PEDIDO = ITE3.CODIGO_PEDIDO
              INNER JOIN PRODUTOS PRO3
              ON ITE3.CODIGO_PRODUTO = PRO3.CODIGO_PRODUTO
             WHERE UPPER(PRO3.NOME_PRODUTO) = 'FEIJAO'
               AND CLI3.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE) AS MAX_QTD_FEIJAO
  FROM CLIENTES CLI
  INNER JOIN PEDIDOS PED
  ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
  INNER JOIN ITENS_PEDIDOS ITE
  ON PED.CODIGO_PEDIDO = ITE.CODIGO_PEDIDO
  INNER JOIN PRODUTOS PRO
  ON ITE.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
 WHERE UPPER(PRO.NOME_PRODUTO) = 'ARROZ'
   AND (CLI.CODIGO_CLIENTE NOT IN (SELECT CLI1.CODIGO_CLIENTE
                                     FROM CLIENTES CLI1
                                    INNER JOIN PEDIDOS PED1
                                    ON CLI1.CODIGO_CLIENTE = PED1.CODIGO_CLIENTE
                                    INNER JOIN ITENS_PEDIDOS ITE1
                                    ON PED1.CODIGO_PEDIDO = ITE1.CODIGO_PEDIDO
                                    INNER JOIN PRODUTOS PRO1
                                    ON ITE1.CODIGO_PRODUTO = PRO1.CODIGO_PRODUTO
                                   WHERE UPPER(PRO1.NOME_PRODUTO) = 'FEIJAO')
        OR((SELECT MAX(ITE2.QUANTIDADE) MAIOR_QUANTIDADE
              FROM CLIENTES CLI2
              INNER JOIN PEDIDOS PED2
              ON CLI2.CODIGO_CLIENTE = PED2.CODIGO_CLIENTE
              INNER JOIN ITENS_PEDIDOS ITE2
              ON PED2.CODIGO_PEDIDO = ITE2.CODIGO_PEDIDO
              INNER JOIN PRODUTOS PRO2
              ON ITE2.CODIGO_PRODUTO = PRO2.CODIGO_PRODUTO
             WHERE UPPER(PRO2.NOME_PRODUTO) = 'ARROZ'
               AND CLI2.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE)
             >
           (SELECT MAX(ITE3.QUANTIDADE) MAIOR_QUANTIDADE
              FROM CLIENTES CLI3
              INNER JOIN PEDIDOS PED3
              ON CLI3.CODIGO_CLIENTE = PED3.CODIGO_CLIENTE
              INNER JOIN ITENS_PEDIDOS ITE3
              ON PED3.CODIGO_PEDIDO = ITE3.CODIGO_PEDIDO
              INNER JOIN PRODUTOS PRO3
              ON ITE3.CODIGO_PRODUTO = PRO3.CODIGO_PRODUTO
             WHERE UPPER(PRO3.NOME_PRODUTO) = 'FEIJAO'
               AND CLI3.CODIGO_CLIENTE = CLI.CODIGO_CLIENTE)
          )
        )
 GROUP BY CLI.CODIGO_CLIENTE
          , CLI.NOME_CLIENTE
          , PRO.NOME_PRODUTO;
          
--ii
CREATE OR REPLACE VIEW PRODUTOS_MEDIDAS AS (
    SELECT PRO.NOME_PRODUTO
         , UE.DESCRICAO_UNIDADE_MEDIDA
      FROM PRODUTOS PRO
      INNER JOIN UNIDADE_MEDIDA UE
      ON PRO.CODIGO_UNIDADE_MEDIDA = UE.CODIGO_UNIDADE_MEDIDA
);

--jj
CREATE OR REPLACE VIEW TOTAL_CLIENTE_VITORIA AS (
SELECT SUM(PED.VALOR_TOTAL) TOTAL_POR_CLIENTE
     , CLI.NOME_CLIENTE
  FROM CLIENTES CLI
  INNER JOIN PEDIDOS PED
  ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
 WHERE UPPER(CLI.CIDADE) = 'VITORIA'
 GROUP BY CLI.NOME_CLIENTE
 HAVING SUM(PED.VALOR_TOTAL) > (SELECT AVG(PED.VALOR_TOTAL)
                                  FROM CLIENTES CLI
                                  INNER JOIN PEDIDOS PED
                                  ON CLI.CODIGO_CLIENTE = PED.CODIGO_CLIENTE
                                 WHERE UPPER(CLI.CIDADE) = 'VILA VELHA'));
                                 