--A
UPDATE ALUNOS
   SET DATA_NASCIMENTO = TO_DATE('29/04/2011', 'DD/MM/YYYY')
 WHERE MATRICULA_ALUNO = 40004;

--B 
UPDATE PROFESSORES
   SET FORMACAO = 'PHD'
 WHERE FORMACAO = 'DOUTORADO';

--C 
UPDATE PROFESSORES
   SET FORMACAO = 'MSC'
 WHERE MATRICULA_PROFESSOR IN (55126, 55133);

--D 
UPDATE DISCIPLINAS
   SET CODIGO_DISCIPLINA_DEPENDENCIA = 31313
 WHERE NOME_DISCIPLINA = 'MACHINE LEARNING';
   
--E
UPDATE OFERTAS
   SET MATRICULA_PROFESSOR = 55128
 WHERE CODIGO_DISCIPLINA   = 12345
   AND MATRICULA_PROFESSOR = 55125;
   
--F
UPDATE ALUNOS_OFERTAS
   SET LIMITE_ALUNOS = 70
 WHERE CODIGO_OFERTA IN (SELECT CODIGO_OFERTA
                          FROM OFERTAS
                         WHERE CODIGO_DISCIPLINA = (SELECT CODIGO_DISCIPLINA
                                                      FROM DISCIPLINAS
                                                     WHERE NOME_DISCIPLINA = 'NATURAL LANGUAGE PROCESSING'));

--G
COMMIT;